# Be sure to change these!
base_url = "https://www.vide.bar"
title = "videbar"

# Sass compilation is required
compile_sass = true

# RSS feed for the blog
generate_feed = true
feed_filename = "rss.xml"

# Optional: enable tags, they are available at base_url/tags
# taxonomies = [
    # {name = "tags"}
# ]

[markdown]
# Code highlighting
highlight_code = true
# Custom theme
extra_syntaxes_and_themes = ["extra-highlight-themes"]
highlight_theme = "darker-nord"

[extra]

# One of: blue, green, orange, pink, red, yellow.
# Defaults to blue.
accent_color = "blue"

# The logo text - defaults to "Terminimal theme"
logo_text = "/videbar"

# The logo link - defaults to base_url.
#logo_home_link = "/take/me/away!"

# Author name: when specified, modifies the default
# copyright text. Apart from author, it will
# contain current year and a link to the theme.
# author = "My Name"

# Copyright text in HTML format. If specified,
# entirely replaces default copyright and author.
# copyright_html = "My custom&nbsp;<b>copyright</b>"

# menu is enabled by adding menu_items (optional)
menu_items = [
    # each of these is optional, name and url are required
    # $BASE_URL is going to be substituted by base_url from configuration
    {name = "home", url = "$BASE_URL"},
    {name = "blog", url = "$BASE_URL/blog"},
    {name = "rss feed", url = "$BASE_URL/rss.xml"},
    {name = "blog archive", url = "$BASE_URL/blog-archive"},

    # set newtab to true to make the link open in new tab
    {name = "github", url = "https://github.com/videbar", newtab = true},
]

# Whether to show links to earlier and later posts
# on each post page (defaults to true).
enable_post_view_navigation = true

# The text shown at the bottom of a post,
# before earlier/later post links.
# Defaults to "Thanks for reading! Read other posts?"
post_view_navigation_prompt = "Thanks for reading! Read other posts?"

# Optional: Global favicon URL and mimetype.
#           Mimetype defaults to "image/x-icon".
#           The URL should point at a file located
#           in your site's "static" directory.
# favicon = "/favicon.png"
# favicon_mimetype = "image/png"

# Optional: Set how <title> elements are rendered.
# Values:
# - "main_only" -- only the main title (`config.title`) is rendered.
# - "page_only" -- only the page title (if defined) is rendered,
#                  falling back to `config.title` if not defined or empty.
# - "combined" -- combine like so: "page_title | main_title",
#                 or if page_title is not defined or empty, fall back to `main_title`
#
# Note that the main (index) page only has the main title.
page_titles = "main_only"
